---
- name: Gather facts from the host
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get OS information
      debug:
        msg: "Operating System: {{ ansible_os_family }} {{ ansible_distribution_version }}"


    - name: Get hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"
